# -*- coding: utf-8 -*-
"""student_perform_deploy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AoeILkCEZ1Ofn5i8R6_wDZ-3PzMoCAPJ
"""

import streamlit as st
import joblib
import pandas as pd


model =joblib.load("best_model.pkl")

st.title("Student Performance")
Sample_Question_Papers_Practiced= st.number_input("Sample Question Papers Practiced",min_value=0,max_value=50)
Hours_Studied= st.number_input("Hours Studied",min_value=0,max_value=24)
Sleep_Hours= st.number_input("Sleep Hours",min_value=0,max_value=24)
Tuition= st.number_input("Tuition (0=No,1=Yes)",min_value=0,max_value=1)
Performance_Index= st.number_input("Performance Index",min_value=0,max_value=100)
Previous_Scores= st.number_input("Previous Scores",min_value=0,max_value=100)


input_data = pd.DataFrame([[
 Sample_Question_Papers_Practiced,
 Hours_Studied,
 Sleep_Hours,
 Tuition,
 Performance_Index
 Previous_Scores
]], columns=model.feature_names_in_)

if st.button("Result"):
  RESULT=model.predict(input_data)
  if RESULT =="negative":
    st.write("NEGETIVE")
  else:
    st.write("POSITIVE")
